name: Gradle Lint

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint with Gradle
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Cache Gradle packages
              uses: actions/cache@v4
              with:
                  path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                    .gradle
                  # Use the wrapper properties and gradle files to version the cache key
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/*.gradle*','**/*.gradle.kts') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                  settings-path: ${{ github.workspace }} # location for the settings.xml file
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
            - name: Lint with Gradle
              run: ./gradlew spotlessCheck

    commitLint:
        name: Commit Lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Commit Lint
              uses: wagoid/commitlint-github-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
